#define APP_BASE 0x0000
#define CAMERA_BASE 0x0100

#define APP_ID_REG (APP_BASE | 0x01)
#define APP_VERSION_REG (APP_BASE | 0x02)
#define CAMERA_STREAM_STATUS_REG (APP_BASE | 0x04)

#define CAM_BRIGHTNESS_REG (CAMERA_BASE | 0x01)
#define CAM_CONTRAST_REG (CAMERA_BASE | 0x02)
#define CAM_SATURATION_REG (CAMERA_BASE | 0x03)
